---
- name: Restart chronyd (Proxmox issue)
  ansible.builtin.systemd_service:
    name: chronyd
    state: restarted

- name: Create k8s Ansible helper directory
  ansible.builtin.file:
    path: "{{ k8s.ansible }}"
    state: directory
    owner: root
    group: root
    mode: '0600'

- name: Set SELinux to permissive mode
  ansible.posix.selinux:
    policy: targeted # default policy on RHEL
    state: permissive

- name: Enable IPv4 packet forwarding accross interfaces
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_file: /etc/sysctl.d/k8s.conf
    state: present
    reload: true

- name: Disable and mask firewalld systemd service - required by CNI plugins
  ansible.builtin.systemd_service:
    name: firewalld.service
    state: stopped
    enabled: false
    masked: true

- name: Install dnf-plugins-core
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present

- name: Add repo for containerd container runtime
  ansible.builtin.shell:
    cmd: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo 
  changed_when: true

- name: Install containerd container runtime
  ansible.builtin.dnf:
    name: containerd.io
    state: latest

- name: Generate default containerd config
  ansible.builtin.shell:
    cmd: containerd config default > /etc/containerd/config.toml
  changed_when: true

- name: Set containerd cgroup driver to Systemd
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = .+'
    replace: 'SystemdCgroup = true'

- name: Restart containerd systemd service
  ansible.builtin.systemd_service:
    name: containerd.service
    daemon_reload: true
    state: restarted
    enabled: true

- name: Add Kubernetes repository
  ansible.builtin.copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: '0644'

- name: Install kubelet, kubectl, kubeadm
  ansible.builtin.dnf:
    name: # we don't have to pin versions because they are pinned in repo definition
      - kubelet
      - kubectl
      - kubeadm
    state: present 
    disable_excludes: all

- name: Enable and restart kubelet systemd service
  ansible.builtin.systemd_service:
    name: kubelet.service
    daemon_reload: true
    state: restarted
    enabled: true
